VBESFB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
    path('',include('base.urls')),
   
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'base'


urlpatterns = [
    path('', views.login, name="login"),
    path('compose/', views.compose, name="compose"),
    path('inbox/', views.inbox, name="inbox"),
    path('sent/', views.sent, name="sent"),
    path('trash/', views.trash, name="trash"),
    path('menu/', views.menu, name="menu")
   
]

base/models.py
from django.db import models

# Create your models here.


class UserDetails(models.Model):
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

class option(models.Model):
    option = models.CharField(max_length=100)

class Details:
    email : str
    password : str

class Compose:
    recipient : str
    subject : str
    body : str

base/forms.py
from django import forms
from . import models

class UserForm(forms.ModelForm):
    class Meta:
        model = models.UserDetails
        fields = ['email','password']
        widgets = {
        'email' : forms.EmailInput(),
        'password': forms.PasswordInput(),
        }

base/views.py
from django.shortcuts import render, redirect
from django import forms
from .models import Details
from .models import Compose
import imaplib,email
from gtts import gTTS
import os
from playsound import playsound
from django.http import HttpResponse
import speech_recognition as sr
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from django.http import JsonResponse
import re

file = "good"
i="0"
passwrd = ""
addr = ""
item =""
subject = ""
body = ""
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()
imap_url = 'imap.gmail.com'
conn = imaplib.IMAP4_SSL(imap_url)
attachment_dir = 'C:/Users/Desktop/'

def texttospeech(text, filename):
    filename = filename + '.mp3'
    flag = True
    while flag:
        try:
            tts = gTTS(text=text, lang='en', slow=False)
            tts.save(filename)
            flag = False
        except:
            print('Trying again')
    playsound(filename)
    os.remove(filename)
    return

def speechtotext(duration):
    global i, addr, passwrd
    r = sr.Recognizer()
    with sr.Microphone() as source:
        r.adjust_for_ambient_noise(source, duration=1)
        playsound('speak.mp3')
        audio = r.listen(source, phrase_time_limit=duration)
    try:
        response = r.recognize_google(audio)
    except:
        response = 'N'
    return response

def convert_special_char(text):
    temp=text
    special_chars = ['attherate','dot','underscore','dollar','hash','star','plus','minus','space','dash']
    for character in special_chars:
        while(True):
            pos=temp.find(character)
            if pos == -1:
                break
            else :
                if character == 'attherate':
                    temp=temp.replace('attherate','@')
                elif character == 'dot':
                    temp=temp.replace('dot','.')
                elif character == 'underscore':
                    temp=temp.replace('underscore','_')
                elif character == 'dollar':
                    temp=temp.replace('dollar','$')
                elif character == 'hash':
                    temp=temp.replace('hash','#')
                elif character == 'star':
                    temp=temp.replace('star','*')
                elif character == 'plus':
                    temp=temp.replace('plus','+')
                elif character == 'minus':
                    temp=temp.replace('minus','-')
                elif character == 'space':
                    temp = temp.replace('space', '')
                elif character == 'dash':
                    temp=temp.replace('dash','-')
    return temp



def login(request):
    global i, addr, passwrd 

    if request.method == 'POST':
        text1 = "Welcome to our Voice Based Email. Please provide your login credentials inorder to continue. "
        texttospeech(text1, file + i)
        i = i + str(1)

        flag = True
        while (flag):
            texttospeech("Enter your Email", file + i)
            i = i + str(1)
            addr = speechtotext(10)
            
            if addr != 'N':
                texttospeech("You meant " + addr + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        addr = addr.strip()
        addr = addr.replace(' ', '')
        addr = addr.lower()
        addr = convert_special_char(addr)
        print(addr)
        request.email = addr

        flag = True
        while (flag):
            texttospeech("Enter your password", file + i)
            i = i + str(1)
            passwrd = speechtotext(10)
            
            if addr != 'N':
                texttospeech("You meant " + passwrd + " say yes to confirm or no to enter again", file + i)
                i = i + str(1)
                say = speechtotext(3)
                if say == 'yes' or say == 'Yes':
                    flag = False
            else:
                texttospeech("could not understand what you meant:", file + i)
                i = i + str(1)
        passwrd = passwrd.strip()
        passwrd = passwrd.replace(' ', '')
        passwrd = passwrd.lower()
        passwrd = convert_special_char(passwrd)
        print(passwrd)

        imap_url = 'imap.gmail.com'
        #passwrd = ''
        #addr = ''
        conn = imaplib.IMAP4_SSL(imap_url)
        try:
            conn.login(addr, passwrd)
            s.login(addr, passwrd)
            texttospeech("You have logged in successfully. You will now be redirected to the menu page.", file + i)
            i = i + str(1)
            return JsonResponse({'result' : 'success'})
        except:
            texttospeech("Invalid Login Details. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})

    
    detail  = Details()
    detail.email = addr
    detail.password = passwrd
    return render(request, 'login.html', {'detail' : detail}) 

def menu(request):
    global i, addr, passwrd
    if request.method == 'POST':
        flag = True
        texttospeech("You are logged into your account. What would you like to do ?", file + i)
        i = i + str(1)
        while(flag):
            texttospeech("To compose an email say compose. To open Inbox folder say Inbox. To open Sent folder say Sent. To open Trash folder say Trash. To Logout say Logout. Do you want me to repeat?", file + i)
            i = i + str(1)
            say = speechtotext(3)
            if say == 'No' or say == 'no':
                flag = False
        texttospeech("Enter your desired action", file + i)
        i = i + str(1)
        act = speechtotext(5)
        act = act.lower()
        if act == 'compose':
            return JsonResponse({'result' : 'compose'})
        elif act == 'inbox':
            return JsonResponse({'result' : 'inbox'})
        elif act == 'sent':
            return JsonResponse({'result' : 'sent'})
        elif act == 'trash':
            return JsonResponse({'result' : 'trash'})
        elif act == 'log out':
            addr = ""
            passwrd = ""
            texttospeech("You have been logged out of your account and now will be redirected back to the login page.",file + i)
            i = i + str(1)
            return JsonResponse({'result': 'logout'})
        else:
            texttospeech("Invalid action. Please try again.", file + i)
            i = i + str(1)
            return JsonResponse({'result': 'failure'})
    elif request.method == 'GET':
        return render(request, 'menu.html')

def compose(request):
    global i, addr, passwrd, s, item, subject, body
    if request.method == 'POST':
        text1 = "You have reached the page where you can compose and send an email. "
        texttospeech(text1, file + i)
        i = i + str(1)
        flag = True
        flag1 = True
        fromaddr = addr
        toaddr = list()
        while flag1:
            while flag:
                texttospeech("enter receiver's email address:", file + i)
                i = i + str(1)
                to = ""
                to = speechtotext(15)
                if to != 'N':
                    
                    texttospeech("You meant " + to + " say yes to confirm or no to enter again", file + i)
                    i = i + str(1)
                    say = speechtotext(5)
                    if say == 'yes' or say == 'Yes':
                        toaddr.append(to)
                        flag = False
                else:
                    texttospeech("could not understand what you meant", file + i)
                    i = i + str(1)
            texttospeech("Do you want to enter more recipients ?  Say yes or no.", file + i)
            i = i + str(1)
            say1 = speechtotext(3)
            if say1 == 'No' or say1 == 'no':
                flag1 = False
            flag = True

        newtoaddr = list()
        for item in toaddr:
            item = item.strip()
            item = item.replace(' ', '')
            item = item.lower()
            item = convert_special_char(item)
            newtoaddr.append(item)
            print(item)

        msg = MIMEMultipart()
        msg['From'] = fromaddr
        msg['To'] = ",".join(newtoaddr)
        flag = True
        while (flag):
            texttospeech("enter subject", file + i)
            i = i + str(1)
            subject = speechtotext(10)
            if subject == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False
        msg['Subject'] = subject
        flag = True
        while flag:
            texttospeech("enter body of the mail", file + i)
            i = i + str(1)
            body = speechtotext(20)
            if body == 'N':
                texttospeech("could not understand what you meant", file + i)
                i = i + str(1)
            else:
                flag = False

        msg.attach(MIMEText(body, 'plain'))
        texttospeech("any attachment? say yes or no", file + i)
        i = i + str(1)
        x = speechtotext(3)
        x = x.lower()
        if x == 'yes':
            texttospeech("Do you want to record an audio and send as an attachment?", file + i)
            i = i + str(1)
            say = speechtotext(2)
            say = say.lower()
            if say == 'yes':
                texttospeech("Enter filename.", file + i)
                i = i + str(1)
                filename = speechtotext(5)
                filename = filename.lower()
                filename = filename + '.mp3'
                filename = filename.replace(' ', '')
                print(filename)

base/templates/compose.html
{% load static %}
<html>
<head>
<!--meta name="viewport" content="width=device-width, initial-scale=1.0"-->  
	<title>COMPOSE</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/compose.css' %}" >
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	
</head>

<body onmousedown = "WhichButtonCompose(event)">
	<div class= "center" >
		<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
		</div>
			<div class="container">
				<div class="text"> COMPOSE </div>
				<form id ="here">

					<script> 
						$(document).ready(function(){
						setInterval(function(){
							  $("#here").load(window.location.href + " #here" );
						}, 1000);
						});
						</script>


					<div class="data">
						<label>Recipient Email Id</label>
						<input placeholder="Enter recipient's email id "required value="{{compose.recipient}}">
					</div>
					<div class="data">
						<label>Subject</label>
						<input placeholder="Enter Subject of mail " type="text" required value="{{compose.subject}}"> 
					</div>
					<div class="data" id="b1">
						<label>Body</label>
						<!-- <input placeholder="Enter body of the mail" type="text"> -->
						<textarea rows="15" cols="50" placeholder="Enter body of mail"placeholder="Type Message"required value="{{compose.body}}"></textarea></textarea>
					</div>
					<div class="btn">
						<div class="inner"></div>
						<button type ="submit">SEND</button>
					</div>
				</form>
			</div>
	</div>
			
	<script>
		function WhichButtonCompose(event){
			$.ajax({
			url: "{% url 'base:compose' %}",
			method: 'POST',
			data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
			success: function (data) {
				if(data.result == 'success'){
					window.location = "{% url 'base:menu' %}";
				}
				else if(data.result == 'failure'){
					window.location = "{% url 'base:compose' %}";
				}
			}
		});
		}
	</script>

</body>
</html>

base/templates/inbox.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
   <title>INBOX PAGE</title>
<!--link rel="stylesheet" href="../css/inbox.css"-->
   <link rel="stylesheet" type="text/css" href="{% static 'css/inbox.css'%}">

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <!--script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"-->

</head>

<body onmousedown = "SendPostRequestInbox(event)">

<div class="wrap">
	<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
	</div>
		<div class="head1">
			<h1 style="text-align:center">INBOX FOLDER</h1>
			<h1 style="text-align:center">What would you like to Do?</h1>
			
		</div>

		<ul class= "options"> 
			<li><a href ="compose.html">UNREAD</a></li>
			<li><a href ="inbox.html">SEARCH</a></li>
			<li><a href ="menu.html">BACK</a></li>
			
			<li><a href ="login.html">LOGOUT</a></li>
		</ul>
</div>

<script>
	function SendPostRequestInbox(event){
		$.ajax({
        url: "{% url 'base:inbox' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'base:menu' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'base:login' %}";
			}
        }
    });
	}
	</script>


</body>
</html>

base/templates/login.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
	<title>LOGIN</title>
	<!--link rel="stylesheet" href = "../css/login.css"-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!--script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script-->

</head>

<body onmousedown = "SendPostRequestHome(event)" >
	<div class= "center" >
		<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
	</div>
			<div class="container">
				<div class="text"> Login </div>
				<form action ="menu.html" method="POST">
				
				
					<div class="data" id ="here">
						<script> 
							$(document).ready(function(){
							setInterval(function(){
								  $("#here").load(window.location.href + " #here" );
							}, 1000);
							});
							</script>
						
						{% csrf_token %}
						<label>Email Id</label>
						<input type="text"placeholder="Email" name="email"required value={{detail.email}} >
					</div>
					<div class="data">
						<label>Password</label>
						<input type="password"placeholder="Password" name="password"required value={{detail.password}} >
					</div>
					<div class="btn">
						<div class="inner"></div>
						<button input href="menu.html" type ="submit">login</button>
					</div>
				</form>
			</div>
	</div>
	<script>
		
		function SendPostRequestHome(event){
			
			$.ajax({
			url: "{% url 'base:login' %}",
			method: "POST",
			data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
			success: function (data) {
				
				if(data.result == "success"){
					
					window.location = "{% url 'base:menu' %}";
				}
				else if(data.result == "failure"){
					window.location = "{% url 'base:login' %}";
				}
			}
		});
		}
		</script>	


</body>
</html>

base/templates/menu.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
<title>MENU PAGE</title>
<!--link rel="stylesheet" href="../css/inbox.css"-->
<link rel="stylesheet" type="text/css" href="{% static 'css/inbox.css'%}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		
</head>


	<body onmousedown = "SendPostRequestOptions(event)">
<div class="wrap">

		<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
	</div>
		
	<div class="head1">
		<h1 style="text-align:center">What would you like to Do?</h1>
		
	</div>

	<ul class= "options"> 
		<li><a href ="{% url 'base:compose' %} ">COMPOSE</a></li>
		<li><a href ="{% url 'base:inbox' %}">INBOX</a></li>
		<li><a href ="{% url 'base:sent' %} ">SENT</a></li>
		<li><a href ="{% url 'base:trash' %} ">TRASH</a></li>
		<li><a href ="{% url 'base:login' %}">LOGOUT</a></li>
	</ul>
</div>
<script>
	function SendPostRequestOptions(event){
		$.ajax({
        url: "{% url 'base:menu' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'compose'){
				window.location = "{% url 'base:compose' %}";
			}
			else if(data.result == 'sent'){
				window.location = "{% url 'base:sent' %}";
			}	
			else if(data.result == 'inbox'){
				window.location = "{% url 'base:inbox' %}";
			}
			else if(data.result == 'trash'){
				window.location = "{% url 'base:trash' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'base:login' %}";
			}
			else if(data.result == 'failure'){
				window.location = "{% url 'base:menu' %}";
			}
        }
    });
	}
	</script>
</body>
</html>

base/templates/sent.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
<title>SENT PAGE</title>
<!--link rel="stylesheet" href="../css/inbox.css"-->
<link rel="stylesheet" type="text/css" href="{% static 'css/inbox.css'%}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		
</head>

<body onmousedown = "SendPostRequestSent(event)">

<div class="wrap">
	<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
	</div>
		<div class="head1">
			<h1 style="text-align:center">SENT FOLDER</h1>
			<h1 style="text-align:center">What would you like to Do?</h1>
			
		</div>

		<ul class= "options"> 
			
			<li><a href ="inbox.html">SEARCH</a></li>
			<li><a href ="menu.html ">BACK</a></li>
			<li><a href ="login.html">LOGOUT</a></li>
		</ul>
</div>

<script>
	function SendPostRequestSent(event){
		$.ajax({
        url: "{% url 'base:sent' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'base:menu' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'base:login' %}";
			}
        }
    });
	}
	</script>

</body>
</html>

base/templates/trash.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
<title>TRASH PAGE</title>
<!--link rel="stylesheet" href="../css/inbox.css"-->
<link rel="stylesheet" type="text/css" href="{% static 'css/inbox.css'%}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		
</head>

<body onmousedown = "SendPostRequestTrash(event)">

<div class="wrap">
	<div class="heading">
		<h2>VOICE BASED EMAIL FOR BLIND </h2>
	</div>
		<div class="head1">
			<h1 style="text-align:center">TRASH FOLDER</h1>
			<h1 style="text-align:center">What would you like to Do?</h1>
			
		</div>

		<ul class= "options"> 
			
			<li><a href ="inbox.html">SEARCH</a></li>
			<li><a href ="menu.html ">BACK</a></li>
			<li><a href ="login.html">LOGOUT</a></li>
		</ul>
</div>
<script>
	function SendPostRequestTrash(event){
		$.ajax({
        url: "{% url 'base:trash' %}",
        method: 'POST',
        data: { 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function (data) {
			if(data.result == 'success'){
				window.location = "{% url 'base:menu' %}";
			}
			else if(data.result == 'logout'){
				window.location = "{% url 'base:login' %}";
			}
        }
    });
	}
	</script>

</body>
</html>